baseURL = "https://midudev.com/"
languageCode = "es-ES"
title = "midudev 👨‍💻 | Frontend, Performance, Javascript, React, CSS"

disableHugoGeneratorInject = true
defaultContentLanguage = "es"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsUseClasses = true

[params]
  description = "Artículos, vídeos, recursos y tutoriales sobre Desarrollo Web, Frontend, Performance Web ⚡️, Javascript ☕️, React ⚛️ y CSS 🎨"
  defaultImage = "/favicon/apple-touch-icon.png"